// Code generated by apigen; DO NOT EDIT.
// This file contains the API description for main

package main

// DataProcessorAPIJSON contains the JSON API description for this file
const DataProcessorAPIJSON = `{
  "apiName": "main",
  "methods": {
    "ProcessUserData": {
      "description": "ProcessUserData processes user data and returns processed result Parameters: - userData: The user data to process (required)",
      "parameters": {
        "userData": {
          "type": "UserData",
          "fields": {
            "Active": {
              "type": "bool",
              "annotations": {
                "json": "active"
              }
            },
            "Age": {
              "type": "int",
              "annotations": {
                "json": "age",
                "validate": "min=0,max=150"
              }
            },
            "Email": {
              "type": "string",
              "annotations": {
                "json": "email",
                "validate": "required,email"
              }
            },
            "ID": {
              "type": "string",
              "annotations": {
                "json": "id",
                "validate": "required"
              }
            },
            "Metadata": {
              "type": "map[string]interface{}",
              "annotations": {
                "json": "metadata"
              }
            },
            "Name": {
              "type": "string",
              "annotations": {
                "json": "name",
                "validate": "required,min=2,max=100"
              }
            }
          }
        }
      }
    },
    "ValidateInput": {
      "description": "ValidateInput validates input data against rules Parameters: - request: The validation request containing data and rules",
      "parameters": {
        "request": {
          "type": "ValidationRequest",
          "fields": {
            "Data": {
              "type": "interface{}",
              "annotations": {
                "json": "data",
                "validate": "required"
              }
            },
            "Rules": {
              "type": "[]string",
              "annotations": {
                "json": "rules"
              }
            },
            "Strict": {
              "type": "bool",
              "annotations": {
                "json": "strict"
              }
            }
          }
        }
      }
    }
  }
}`
